.PHONY: all clean

all: FalWk2.pdf

FalWk2.pdf: FalWk2.tex
	xelatex FalWk2.tex

clean:
	rm -f *.aux *.bbl *.blg *.log *.out *.toc *.lof *.lot *.lol *.loa *.lox *.xdv *.pdf
	rm -f *.fdb_latexmk *.fls *.synctex.gz